### ISSUE TITLE
Feature: Ability to Change Labels

### ISSUE THREAD

**Issue by Armandeus66** [scari08/pf2e-chances#10]
We have the ability to change the colors. Thanks! How about the ability to change the labels? For example, I'd like to make things simple and change the labels to CF, F, S, and CS. Some people might like to translate the text to their language.

**Comment by DarkMatter26** [comment]
+1 for translate this

**Comment by scari08** [comment]
Added the option to set custom labels in 1.3.0
This would let the gm decide whatever they want to see as a label, even your translations
