### ISSUE TITLE
[Feature] Standout Text Color

### ISSUE THREAD

**Issue by ChasarooniZ** [scari08/pf2e-chances#4]
Maybe an option to change text color, or a high contrast mode etc. Makes it hard to use this module with something like Dorako UI as is
![image](https://github.com/user-attachments/assets/8c1fedcf-61bc-4797-b165-64f51fb9c9b8)

**Comment by scari08** [comment]
Dorako UI shuold already support dark theme in recent updates, but I added a setting to override with custom colors anyway
