### ISSUE TITLE
[Settings/Layout] Improved colors using PF2 Trade Colors

### ISSUE THREAD

**Issue by apoapostolov** [scari08/pf2e-chances#5]
Critical Failure: #c42522
Failure: #874644
Success: #002564
Critical: #448746

Using Failure and Success based on PF2 Layout Colors (not remaster), then color compatibility to get Critical (dark green) and color mixing with red to get flaring red compatible with PF2 regal red. 

Best of all, if the colors are configurable from the Settings.

**Comment by scari08** [comment]
added setting to override with coustom colors in 1.2.2
